name: Typescript Pull Request Check

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "packages/typescript/**"
      - ".github/workflows/typescript-pr-check.yml"

  pull_request:
    branches: [main]
    paths:
      - "packages/typescript/**"
      - ".github/workflows/typescript-pr-check.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checking-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: ./packages/typescript/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./packages/typescript
        run: pnpm install
      - name: Run Prettier check
        working-directory: ./packages/typescript
        run: pnpm format:check
      - name: Run lint
        working-directory: ./packages/typescript
        run: pnpm lint
      - name: Run test
        working-directory: ./packages/typescript
        run: pnpm test
      - name: Run build
        working-directory: ./packages/typescript
        run: pnpm build
      - name: Check if dist and types are created
        run: |
          if [ ! -d "./packages/typescript/dist" ]; then
            echo "dist directory is not created"
            exit 1
          fi
          if [ ! -d "./packages/typescript/types" ]; then
            echo "types directory is not created"
            exit 1
          fi
          echo "dist and types directory are created"
